name: Get Edge Driver Thumbprint

on: [push, pull_request]

jobs:
  extract_thumbprint:
    runs-on: windows-2022  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download EdgeDriver
        run: |
          Invoke-WebRequest -Uri "https://msedgedriver.azureedge.net/132.0.2957.127/edgedriver_win64.zip" -OutFile "edgedriver.zip"
      - name: Unzip EdgeDriver
        run: |
          Expand-Archive -Path "edgedriver.zip" -DestinationPath "edgedriver"
      - name: Get Certificate Thumbprint
        run: |
          $certPath = "edgedriver/msedgedriver.exe"  # Adjust if necessary based on extraction
          $cert = Get-AuthenticodeSignature -FilePath $certPath
          Write-Output "Thumbprint: $($cert.SignerCertificate.Thumbprint)"
