name: Deploy

on:
  push:
    branches:
      - git2.47.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/[email protected]
        with:
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Generate auth hosts
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # Example deployment step (replace with your actual deployment commands)
      - name: SSH and run a command
        run: |
          ssh -o StrictHostKeyChecking=no  [email protected] "echo 'Deployment successful!'"
