name: Install Git 2.47.1 and Git-FTP

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (if needed)
        uses: actions/checkout@v4

      - name: Install Git using apt
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Verify Git version
        run: git --version

      - name: Install git-ftp
        run: sudo apt-get install -y git-ftp

      - name: Add SSH Host Keys
        run: |
          sudo ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> /etc/ssh/ssh_known_hosts
          sudo ssh-keyscan -t rsa ssh.dev.azure.com >> /etc/ssh/ssh_known_hosts

