name: LibreSSLTest

on:
  workflow_dispatch:
    inputs:
      libressl_version:
        description: LibreSSL Version
        required: true
        default: '4.0.0'
        type: string

jobs:
  build-libressl-linux-arm64-on-ubuntu-24-04:
    name: Build LibreSSL Linux ARM64 on Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - name: LibreSSL Version
        run: echo Build LibreSSL ${{ inputs.libressl_version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build
        run: |
          curl -O "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${{ inputs.libressl_version }}.tar.gz"
          tar xvfz ./libressl-${{ inputs.libressl_version }}.tar.gz
          cd ./libressl-${{ inputs.libressl_version }}
          docker run \
            --rm \
            -v "$PWD":/usr/src/libressl \
            -w /usr/src/libressl \
            arm64v8/gcc:8.1 \
            /bin/bash -c "./configure --enable-libtls-only --with-pic --disable-dependency-tracking && make -j4"
          cd ..
          mkdir -p ./libs/linux-arm64
          cp ./libressl-${{ inputs.libressl_version }}/tls/.libs/libtls.a ./libs/linux-arm64/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LibreSSL-linux-arm64-on-ubuntu-24-04
          retention-days: 2
          path: |
            ./libs/linux-arm64/libtls.a
          if-no-files-found: error

  build-libressl-linux-arm64-on-ubuntu-22-04:
    name: Build LibreSSL Linux ARM64 on Ubuntu 22.04
    runs-on: ubuntu-22-04
    steps:
      - name: LibreSSL Version
        run: echo Build LibreSSL ${{ inputs.libressl_version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build
        run: |
          curl -O "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${{ inputs.libressl_version }}.tar.gz"
          tar xvfz ./libressl-${{ inputs.libressl_version }}.tar.gz
          cd ./libressl-${{ inputs.libressl_version }}
          docker run \
            --rm \
            -v "$PWD":/usr/src/libressl \
            -w /usr/src/libressl \
            arm64v8/gcc:8.1 \
            /bin/bash -c "./configure --enable-libtls-only --with-pic --disable-dependency-tracking && make -j4"
          cd ..
          mkdir -p ./libs/linux-arm64
          cp ./libressl-${{ inputs.libressl_version }}/tls/.libs/libtls.a ./libs/linux-arm64/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LibreSSL-linux-arm64-on-ubuntu-22-04
          retention-days: 2
          path: |
            ./libs/linux-arm64/libtls.a
          if-no-files-found: error
