name: Install Dependencies

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update 2>/dev/null
        sudo apt-get install -y libgl1-mesa-dev libegl1-mesa-dev mesa-common-dev 2>/dev/null
    - name: Verify installed dependencies
      run: |
        apt list --installed | grep -E 'libgl1-mesa-dev|libegl1-mesa-dev|mesa-common-dev'
