name: Install Node.js using Snap

on: [push, pull_request]

jobs:
  install-node:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        run: sudo snap install node --classic --channel=${{ inputs.node_version }}
        
      - name: Verify Node.js version
        run: node -v
