name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js using snap
      run: sudo snap install node --classic --channel=${{ inputs.node_version }}

    - name: Verify Node.js installation
      run: node --version

    - name: Check for package.json
      run: test -f package.json || { echo "package.json not found"; exit 1; }

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm test
