name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Run PowerShell script
        run: |
          pwsh -c '
          $targetDirName = "runner-images"
          git clone --quiet "https://github.com/actions/runner-images.git" $targetDirName
          Set-Location $targetDirName
          $runnerTag = git tag --list "$image*" | Select -Last 1
          Write-Output "Latest runner tag: $runnerTag"
          '
