name: Setup .NET 8.0.x

on:
  push:
    branches:
      - Ddnett
  pull_request:
    branches:
      - Ddnett

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 8.0.x
      run: |
        wget https://dot.net/v1/dotnet-install.sh
        chmod +x ./dotnet-install.sh
        ./dotnet-install.sh --channel 8.0

    - name: Display .NET SDK version
      run: ~/.dotnet/dotnet --version
