name: Generate WSL2 Checksum

on: [push, pull_request]

jobs:
  generate-checksum:
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install openssl

      - name: Generate WSL2 image checksum
        run: |
          # Replace `wsl2-image.tar` with the actual WSL2 image file
          openssl dgst -sha256 wsl2-image.tar > checksum.txt

      - name: Print checksum
        run: |
          type checksum.txt

      - name: Upload checksum
        uses: actions/upload-artifact@v2
        with:
          name: wsl2-checksum
          path: checksum.txt
