
name: Generate SHA256 Checksum on Windows (WSL2)

on: [push, pull_request]

jobs:
  checksum:
    runs-on: windows-2025

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate SHA256 Checksum on WSL2
      run: |
        # Define the path to the file you want to checksum
        $filePath = "C:\\path\\to\\your\\file.txt"

        # Ensure WSL2 is installed and available
        if (-Not (Test-Path "C:\Windows\System32\wsl.exe")) {
          Write-Error "WSL is not installed or accessible on this system."
          exit 1
        }

        # Run the WSL2 command to calculate the SHA256 checksum
        $wslCommand = "wsl sha256sum '$filePath'"
        
        # Execute the command and capture the result
        $checksum = Invoke-Expression $wslCommand
        
        # Output the checksum to the console
        Write-Host "SHA256 Checksum: $checksum"

    - name: Print SHA256 checksum
      run: |
        echo "SHA256 checksum generation complete!"
