
name: Generate SHA256 Checksum on Windows (WSL2)

on: [push, pull_request]

jobs:
  checksum:
    runs-on: windows-2025

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up WSL2
      uses: wslbuilder/setup-wsl@v2.0

    - name: Generate SHA256 Checksum on WSL2
      run: |
        # Path to the file you want to checksum (adjust if necessary)
        $filePath = "C:\\path\\to\\your\\file.txt"

        # Ensure WSL2 is ready and calculate the checksum using sha256sum
        $wslCommand = "wsl sha256sum '$filePath'"
        
        # Run the WSL2 command to generate SHA256 checksum
        $checksum = Invoke-Expression $wslCommand
        Write-Host "SHA256 Checksum: $checksum"

    - name: Print SHA256 checksum
      run: |
        echo "SHA256 checksum generation complete!"
